# Bandit security linter configuration
#
# Bandit doesn’t read pyproject.toml, so keep this file
# at the project root (or in a config/ directory).

# Directories to skip entirely
exclude_dirs:
  - tests
  - docs
  - build

# Specific Bandit tests to skip (e.g., assert usage)
skips:
  - B101  # assert used
  - B110  # try/except: pass

# Only scan your application code
targets:
  - csvtree

# Filter findings by minimum severity/confidence
severity: MEDIUM
confidence: MEDIUM
