name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Initialize environment
        run: uv sync

      - name: Lint
        run: make lint

      - name: Typecheck
        run: make typecheck

      - name: Security scan
        run: make security

# Commenting this portion until some tests are written
#      - name: Test
#        run: make test
